const taskLists = [
  'Learn React',
  'Learn JavaScript',
  'Learn Tailwind',
  'Learn Vue',
  'Learn Boostrap',
  'Learn Node',
  'Learn Python',
  'Learn Java',
  'Learn C#',
  'Learn C++',
  'Learn Swift',
  'Learn Go',
  'Learn PHP',
  'Learn Ruby',
  'Learn Scala',
  'Learn Kotlin',
  'Learn Swift',
  'Learn Swift',
  'Learn Swift',
  'Learn Swift',
  'Learn Swift',
  'Learn Swift',
  'Learn Swift',
]

export { taskLists }
